server:
  port: 8080
  servlet:
    context-path: /
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:

spring:
  profiles:
    active: lyn
---
spring:
  profiles: cq
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cskaoyanmall?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
myoss:
  bucket: alexcheng
  endpoint: oss-cn-hangzhou.aliyuncs.com
  access-key: LTAILjvmsUY8cQer
  secret: dWt6iskaoC09bfcsu5ZchwHjJd0MvL
---
spring:
  profiles: lyn
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_mall?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
myoss:
  bucket: icefloe-rot
  endpoint: oss-cn-beijing.aliyuncs.com
  access-key: LTAIuMqEy3okWKAu
  secret: 3izazmEzf0WsPrQNtZ1XXQMOjdqyv3
---
spring:
  profiles: xy
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/j14_mall?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

myoss:
  bucket: sszskkk
  endpoint: oss-cn-beijing.aliyuncs.com
  access-key: LTAIGPLBx9u8xMBf
  secret: uABGwnf5zi40va95eUUYmywBRTOgrn

---
spring:
  profiles: hxf
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/j14_mall?serverTimezone=GMT
    username: root
    password: 123456
---
spring:
  profiles: zw
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_mall?characterEncoding=utf-8
    username: root
    password: 325601
myoss:
  bucket: cskaoyan-dom
  endpoint: oss-cn-beijing.aliyuncs.com
  access-key: LTAI3sdJdh79t29f
  secret: xGTmC2q655HzuQmjqcUNtNmkc0whLl

